# docker-compose.yml
version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      VITE_API_URL: http://api-dev.from-a2b.fr
