# docker-compose.yml
version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      API_URL: http://localhost:32769
