name: Build

on:
  #  pull_request:
  #    branches:
  #      - main
  #      - develop

  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js with PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      #      - name: Install Dependencies
      #        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{tsx,md}